spring:
  application:
    name: alhamfirst
  profiles:
    include: oauth

  datasource:
    url: jdbc:mariadb://localhost:3306/alfirst?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
  data:
    uri: mongodb://localhost:27017/alham_mongo
    database: alham_mongo

  ai:
    openai:
      api-key:
      chat:
        options:
          model: gpt-4o-mini
        enabled: true

