spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: # google API의 범위 값
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
#          kakao:
#            client-id: ${KAKAO_CLIENT}
#            client-secret: ${KAKAO_SECRET}
#            redirect-uri: {baseUrl}/login/oauth2/code/kakao
#            client-authentication-method: client_secret_post # kakao는 인증 토큰 발급 요청 메서드가 post이다. (최근 버전에는 작성 방법이 이렇게 바뀌었다.)
#            authorization-grant-type: authorization_code
#            scope: # kakao 개인 정보 동의 항목 설정의 ID 값
#              - profile_nickname
#              - profile_image
#              - account_email
#            client-name: kakao

        # kakao provider 설정